"""Add visitor_session to voting and ballot

Revision ID: 21f7749ad9a9
Revises: 672ece27a4e0
Create Date: 2026-07-25 13:38:08.535651+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21f7749ad9a9'
down_revision: Union[str, Sequence[str], None] = '672ece27a4e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ballots', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.add_column('ballots', sa.Column('visitor_session_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_ballots_user_id'), 'ballots', ['user_id'], unique=False)
    op.create_index(op.f('ix_ballots_visitor_session_id'), 'ballots', ['visitor_session_id'], unique=False)
    op.create_foreign_key(op.f('fk_ballots_visitor_session_id_visitor_sessions'), 'ballots', 'visitor_sessions', ['visitor_session_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_ballots_user_id_identity_users'), 'ballots', 'identity_users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('voting_sessions', sa.Column('visitor_session_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_voting_sessions_visitor_session_id'), 'voting_sessions', ['visitor_session_id'], unique=False)
    op.create_foreign_key(op.f('fk_voting_sessions_visitor_session_id_visitor_sessions'), 'voting_sessions', 'visitor_sessions', ['visitor_session_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_voting_sessions_visitor_session_id_visitor_sessions'), 'voting_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_voting_sessions_visitor_session_id'), table_name='voting_sessions')
    op.drop_column('voting_sessions', 'visitor_session_id')
    op.drop_constraint(op.f('fk_ballots_user_id_identity_users'), 'ballots', type_='foreignkey')
    op.drop_constraint(op.f('fk_ballots_visitor_session_id_visitor_sessions'), 'ballots', type_='foreignkey')
    op.drop_index(op.f('ix_ballots_visitor_session_id'), table_name='ballots')
    op.drop_index(op.f('ix_ballots_user_id'), table_name='ballots')
    op.drop_column('ballots', 'visitor_session_id')
    op.drop_column('ballots', 'user_id')
    # ### end Alembic commands ###
