"""Add Voter Management Models

Revision ID: 3bda22c92f9a
Revises: 21f7749ad9a9
Create Date: 2026-08-13 22:44:33.554346+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision: str = '3bda22c92f9a'
down_revision: Union[str, Sequence[str], None] = '21f7749ad9a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voter_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('election_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', app.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deleted_by'], ['identity_users.id'], name=op.f('fk_voter_groups_deleted_by_identity_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], name=op.f('fk_voter_groups_election_id_elections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voter_groups')),
    sa.UniqueConstraint('election_id', 'name', name='uq_voter_group_name_per_election')
    )
    op.create_index(op.f('ix_voter_groups_election_id'), 'voter_groups', ['election_id'], unique=False)
    op.create_index(op.f('ix_voter_groups_is_deleted'), 'voter_groups', ['is_deleted'], unique=False)
    op.create_table('eligible_voters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('election_id', sa.Uuid(), nullable=False),
    sa.Column('voter_identifier', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=15), nullable=True),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('has_voted', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', app.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deleted_by'], ['identity_users.id'], name=op.f('fk_eligible_voters_deleted_by_identity_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], name=op.f('fk_eligible_voters_election_id_elections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['voter_groups.id'], name=op.f('fk_eligible_voters_group_id_voter_groups'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eligible_voters')),
    sa.UniqueConstraint('election_id', 'voter_identifier', name='uq_voter_identifier_per_election')
    )
    op.create_index(op.f('ix_eligible_voters_election_id'), 'eligible_voters', ['election_id'], unique=False)
    op.create_index(op.f('ix_eligible_voters_is_deleted'), 'eligible_voters', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eligible_voters_is_deleted'), table_name='eligible_voters')
    op.drop_index(op.f('ix_eligible_voters_election_id'), table_name='eligible_voters')
    op.drop_table('eligible_voters')
    op.drop_index(op.f('ix_voter_groups_is_deleted'), table_name='voter_groups')
    op.drop_index(op.f('ix_voter_groups_election_id'), table_name='voter_groups')
    op.drop_table('voter_groups')
    # ### end Alembic commands ###
