"""organization_foundation

Revision ID: 4862091312e5
Revises: b06526941208
Create Date: 2026-07-16 23:11:30.580526+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app

# revision identifiers, used by Alembic.
revision: str = '4862091312e5'
down_revision: Union[str, Sequence[str], None] = 'b06526941208'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'ARCHIVED', 'PENDING_VERIFICATION', name='organization_status_enum'), nullable=False),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', app.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('organization_branding',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('logo_url', sa.String(length=1024), nullable=True),
    sa.Column('banner_url', sa.String(length=1024), nullable=True),
    sa.Column('favicon_url', sa.String(length=1024), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('secondary_color', sa.String(length=7), nullable=True),
    sa.Column('accent_color', sa.String(length=7), nullable=True),
    sa.Column('theme_preference', sa.String(length=20), nullable=False),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_branding_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_branding')),
    sa.UniqueConstraint('organization_id', name=op.f('uq_organization_branding_organization_id'))
    )
    op.create_table('organization_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('default_timezone', sa.String(length=100), nullable=False),
    sa.Column('date_format', sa.String(length=50), nullable=False),
    sa.Column('time_format', sa.String(length=50), nullable=False),
    sa.Column('default_event_visibility', sa.String(length=50), nullable=False),
    sa.Column('default_result_visibility', sa.String(length=50), nullable=False),
    sa.Column('default_voting_rules', sa.Text(), nullable=True),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_settings_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_settings')),
    sa.UniqueConstraint('organization_id', name=op.f('uq_organization_settings_organization_id'))
    )
    op.create_table('organization_subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('current_plan', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELED', 'TRIALING', 'PAST_DUE', 'UNPAID', name='subscription_status_enum'), nullable=False),
    sa.Column('is_trial', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('trial_expires_at', sa.String(length=100), nullable=True),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_subscriptions_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_subscriptions')),
    sa.UniqueConstraint('organization_id', name=op.f('uq_organization_subscriptions_organization_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization_subscriptions')
    op.drop_table('organization_settings')
    op.drop_table('organization_branding')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
