"""Add ElectionCategory model

Revision ID: 5286460ccbcd
Revises: baf378ddf0aa
Create Date: 2026-07-23 00:37:15.425156+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app

# revision identifiers, used by Alembic.
revision: str = '5286460ccbcd'
down_revision: Union[str, Sequence[str], None] = 'baf378ddf0aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('election_categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('election_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('category_type', sa.Enum('POSITION', 'CATEGORY', name='categorytype'), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('max_winners', sa.Integer(), nullable=False),
    sa.Column('voting_method', sa.Enum('FIRST_PAST_THE_POST', 'APPROVAL', 'RANKED_CHOICE', 'STV', name='votingmethod'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', app.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deleted_by'], ['identity_users.id'], name=op.f('fk_election_categories_deleted_by_identity_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], name=op.f('fk_election_categories_election_id_elections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_election_categories'))
    )
    op.create_index(op.f('ix_election_categories_election_id'), 'election_categories', ['election_id'], unique=False)
    op.create_index(op.f('ix_election_categories_is_deleted'), 'election_categories', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_election_categories_is_deleted'), table_name='election_categories')
    op.drop_index(op.f('ix_election_categories_election_id'), table_name='election_categories')
    op.drop_table('election_categories')
    # ### end Alembic commands ###
