"""election_engine_ui_fields

Revision ID: 609325742bca
Revises: 678e78566eb4
Create Date: 2026-07-22 12:45:19.507661+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '609325742bca'
down_revision: Union[str, Sequence[str], None] = '678e78566eb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elections', sa.Column('automatically_publish_results', sa.Boolean(), nullable=False))
    op.add_column('elections', sa.Column('require_voter_verification', sa.Boolean(), nullable=False))
    op.drop_column('elections', 'allow_result_preview')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elections', sa.Column('allow_result_preview', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('elections', 'require_voter_verification')
    op.drop_column('elections', 'automatically_publish_results')
    # ### end Alembic commands ###
