"""add_platform_identity_and_invitations

Revision ID: 616b7b23d308
Revises: fc334f5264cb
Create Date: 2026-07-21 11:34:58.543108+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision: str = '616b7b23d308'
down_revision: Union[str, Sequence[str], None] = 'fc334f5264cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rbac_platform_permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rbac_platform_permissions'))
    )
    op.create_index(op.f('ix_rbac_platform_permissions_key'), 'rbac_platform_permissions', ['key'], unique=True)
    op.create_table('rbac_platform_roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rbac_platform_roles'))
    )
    op.create_index(op.f('ix_rbac_platform_roles_name'), 'rbac_platform_roles', ['name'], unique=True)
    op.create_table('rbac_platform_identities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity_users.id'], name=op.f('fk_rbac_platform_identities_user_id_identity_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rbac_platform_identities'))
    )
    op.create_index(op.f('ix_rbac_platform_identities_user_id'), 'rbac_platform_identities', ['user_id'], unique=True)
    op.create_table('rbac_platform_invitations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('role_ids', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('inviter_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.String(length=50), nullable=False),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inviter_id'], ['identity_users.id'], name=op.f('fk_rbac_platform_invitations_inviter_id_identity_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rbac_platform_invitations'))
    )
    op.create_index(op.f('ix_rbac_platform_invitations_email'), 'rbac_platform_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_rbac_platform_invitations_token'), 'rbac_platform_invitations', ['token'], unique=True)
    op.create_table('rbac_platform_role_permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['rbac_platform_permissions.id'], name=op.f('fk_rbac_platform_role_permissions_permission_id_rbac_platform_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['rbac_platform_roles.id'], name=op.f('fk_rbac_platform_role_permissions_role_id_rbac_platform_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rbac_platform_role_permissions')),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_platform_role_permission')
    )
    op.create_index(op.f('ix_rbac_platform_role_permissions_permission_id'), 'rbac_platform_role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_rbac_platform_role_permissions_role_id'), 'rbac_platform_role_permissions', ['role_id'], unique=False)
    op.create_table('rbac_user_platform_roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['rbac_platform_roles.id'], name=op.f('fk_rbac_user_platform_roles_role_id_rbac_platform_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['identity_users.id'], name=op.f('fk_rbac_user_platform_roles_user_id_identity_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rbac_user_platform_roles')),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_platform_role')
    )
    op.create_index(op.f('ix_rbac_user_platform_roles_role_id'), 'rbac_user_platform_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_rbac_user_platform_roles_user_id'), 'rbac_user_platform_roles', ['user_id'], unique=False)
    op.create_table('support_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('request_type', sa.String(length=50), server_default='GENERAL', nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'COMPLETED', 'CANCELLED', name='support_request_status_enum'), server_default='PENDING', nullable=False),
    sa.Column('resolved_at', app.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_support_requests_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['identity_users.id'], name=op.f('fk_support_requests_requested_by_identity_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support_requests'))
    )
    op.create_index(op.f('ix_support_requests_organization_id'), 'support_requests', ['organization_id'], unique=False)
    op.create_index(op.f('ix_support_requests_requested_by'), 'support_requests', ['requested_by'], unique=False)
    op.create_table('support_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('platform_user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('support_request_id', sa.Uuid(), nullable=True),
    sa.Column('access_level', sa.String(length=50), server_default='Platform Support', nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('expires_at', app.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'TERMINATED', name='session_status_enum'), server_default='ACTIVE', nullable=False),
    sa.Column('ended_at', app.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_support_sessions_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_user_id'], ['identity_users.id'], name=op.f('fk_support_sessions_platform_user_id_identity_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['support_request_id'], ['support_requests.id'], name=op.f('fk_support_sessions_support_request_id_support_requests'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support_sessions'))
    )
    op.create_index(op.f('ix_support_sessions_organization_id'), 'support_sessions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_support_sessions_platform_user_id'), 'support_sessions', ['platform_user_id'], unique=False)
    op.create_index(op.f('ix_support_sessions_support_request_id'), 'support_sessions', ['support_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_support_sessions_support_request_id'), table_name='support_sessions')
    op.drop_index(op.f('ix_support_sessions_platform_user_id'), table_name='support_sessions')
    op.drop_index(op.f('ix_support_sessions_organization_id'), table_name='support_sessions')
    op.drop_table('support_sessions')
    op.drop_index(op.f('ix_support_requests_requested_by'), table_name='support_requests')
    op.drop_index(op.f('ix_support_requests_organization_id'), table_name='support_requests')
    op.drop_table('support_requests')
    op.drop_index(op.f('ix_rbac_user_platform_roles_user_id'), table_name='rbac_user_platform_roles')
    op.drop_index(op.f('ix_rbac_user_platform_roles_role_id'), table_name='rbac_user_platform_roles')
    op.drop_table('rbac_user_platform_roles')
    op.drop_index(op.f('ix_rbac_platform_role_permissions_role_id'), table_name='rbac_platform_role_permissions')
    op.drop_index(op.f('ix_rbac_platform_role_permissions_permission_id'), table_name='rbac_platform_role_permissions')
    op.drop_table('rbac_platform_role_permissions')
    op.drop_index(op.f('ix_rbac_platform_invitations_token'), table_name='rbac_platform_invitations')
    op.drop_index(op.f('ix_rbac_platform_invitations_email'), table_name='rbac_platform_invitations')
    op.drop_table('rbac_platform_invitations')
    op.drop_index(op.f('ix_rbac_platform_identities_user_id'), table_name='rbac_platform_identities')
    op.drop_table('rbac_platform_identities')
    op.drop_index(op.f('ix_rbac_platform_roles_name'), table_name='rbac_platform_roles')
    op.drop_table('rbac_platform_roles')
    op.drop_index(op.f('ix_rbac_platform_permissions_key'), table_name='rbac_platform_permissions')
    op.drop_table('rbac_platform_permissions')
    # ### end Alembic commands ###
