"""Add paid voting and contests

Revision ID: 672ece27a4e0
Revises: eef19b70fa67
Create Date: 2026-07-25 13:23:31.208839+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app


# revision identifiers, used by Alembic.
revision: str = '672ece27a4e0'
down_revision: Union[str, Sequence[str], None] = 'eef19b70fa67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitor_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('election_id', sa.Uuid(), nullable=False),
    sa.Column('visitor_token', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=1024), nullable=True),
    sa.Column('expires_at', app.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], name=op.f('fk_visitor_sessions_election_id_elections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visitor_sessions'))
    )
    op.create_index(op.f('ix_visitor_sessions_election_id'), 'visitor_sessions', ['election_id'], unique=False)
    op.create_index(op.f('ix_visitor_sessions_visitor_token'), 'visitor_sessions', ['visitor_token'], unique=True)
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('election_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('visitor_session_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', 'CANCELLED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('verified_at', app.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], name=op.f('fk_payments_election_id_elections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['identity_users.id'], name=op.f('fk_payments_user_id_identity_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visitor_session_id'], ['visitor_sessions.id'], name=op.f('fk_payments_visitor_session_id_visitor_sessions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index(op.f('ix_payments_election_id'), 'payments', ['election_id'], unique=False)
    op.create_index(op.f('ix_payments_reference'), 'payments', ['reference'], unique=True)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_index(op.f('ix_payments_visitor_session_id'), 'payments', ['visitor_session_id'], unique=False)
    op.create_table('vote_wallets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('election_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('visitor_session_id', sa.Uuid(), nullable=True),
    sa.Column('available_votes', sa.Integer(), nullable=False),
    sa.Column('reserved_votes', sa.Integer(), nullable=False),
    sa.Column('used_votes', sa.Integer(), nullable=False),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], name=op.f('fk_vote_wallets_election_id_elections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['identity_users.id'], name=op.f('fk_vote_wallets_user_id_identity_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visitor_session_id'], ['visitor_sessions.id'], name=op.f('fk_vote_wallets_visitor_session_id_visitor_sessions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vote_wallets'))
    )
    op.create_index(op.f('ix_vote_wallets_election_id'), 'vote_wallets', ['election_id'], unique=False)
    op.create_index(op.f('ix_vote_wallets_user_id'), 'vote_wallets', ['user_id'], unique=False)
    op.create_index(op.f('ix_vote_wallets_visitor_session_id'), 'vote_wallets', ['visitor_session_id'], unique=False)
    op.create_table('vote_credit_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('wallet_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_type', sa.Enum('PAYMENT', 'BALLOT', 'REFUND', 'RESERVATION', 'RELEASE', name='votecredittransactiontype'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['vote_wallets.id'], name=op.f('fk_vote_credit_transactions_wallet_id_vote_wallets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vote_credit_transactions'))
    )
    op.create_index(op.f('ix_vote_credit_transactions_reference_id'), 'vote_credit_transactions', ['reference_id'], unique=False)
    op.create_index(op.f('ix_vote_credit_transactions_wallet_id'), 'vote_credit_transactions', ['wallet_id'], unique=False)
    op.add_column('ballot_selections', sa.Column('vote_weight', sa.Integer(), nullable=False, server_default=sa.text('1')))
    
    # Create enum type before adding column
    public_verification_enum = postgresql.ENUM('NONE', 'EMAIL_OTP', 'SMS_OTP', 'PHONE', 'PLATFORM_ACCOUNT', name='publicverificationmethod')
    public_verification_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('elections', sa.Column('public_verification_method', public_verification_enum, nullable=False, server_default=sa.text("'NONE'")))
    op.execute("ALTER TYPE electiontype ADD VALUE IF NOT EXISTS 'contest'")
    
    op.add_column('elections', sa.Column('is_paid', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('elections', sa.Column('cost_per_vote', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('elections', sa.Column('currency', sa.String(length=10), nullable=True))
    op.add_column('elections', sa.Column('min_payment', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('elections', sa.Column('max_payment', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('elections', sa.Column('preset_amounts', sa.JSON(), nullable=True))
    op.add_column('elections', sa.Column('allow_custom_amount', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('voting_selections', sa.Column('vote_weight', sa.Integer(), nullable=False, server_default=sa.text('1')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voting_selections', 'vote_weight')
    op.drop_column('elections', 'allow_custom_amount')
    op.drop_column('elections', 'preset_amounts')
    op.drop_column('elections', 'max_payment')
    op.drop_column('elections', 'min_payment')
    op.drop_column('elections', 'currency')
    op.drop_column('elections', 'cost_per_vote')
    op.drop_column('elections', 'is_paid')
    op.drop_column('elections', 'public_verification_method')
    op.drop_column('ballot_selections', 'vote_weight')
    op.drop_index(op.f('ix_vote_credit_transactions_wallet_id'), table_name='vote_credit_transactions')
    op.drop_index(op.f('ix_vote_credit_transactions_reference_id'), table_name='vote_credit_transactions')
    op.drop_table('vote_credit_transactions')
    op.drop_index(op.f('ix_vote_wallets_visitor_session_id'), table_name='vote_wallets')
    op.drop_index(op.f('ix_vote_wallets_user_id'), table_name='vote_wallets')
    op.drop_index(op.f('ix_vote_wallets_election_id'), table_name='vote_wallets')
    op.drop_table('vote_wallets')
    op.drop_index(op.f('ix_payments_visitor_session_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_election_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_visitor_sessions_visitor_token'), table_name='visitor_sessions')
    op.drop_index(op.f('ix_visitor_sessions_election_id'), table_name='visitor_sessions')
    op.drop_table('visitor_sessions')
    # ### end Alembic commands ###
