"""add rbac models

Revision ID: 6f8bacc33dda
Revises: 8c43e8913b56
Create Date: 2026-07-18 19:25:34.720101+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.database.types


# revision identifiers, used by Alembic.
revision: str = '6f8bacc33dda'
down_revision: Union[str, Sequence[str], None] = '8c43e8913b56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rbac_permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rbac_permissions'))
    )
    op.create_index(op.f('ix_rbac_permissions_key'), 'rbac_permissions', ['key'], unique=True)
    op.create_table('rbac_roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_rbac_roles_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rbac_roles'))
    )
    op.create_index(op.f('ix_rbac_roles_organization_id'), 'rbac_roles', ['organization_id'], unique=False)
    op.create_table('rbac_membership_roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('membership_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['identity_users.id'], name=op.f('fk_rbac_membership_roles_assigned_by_identity_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], name=op.f('fk_rbac_membership_roles_membership_id_memberships'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['rbac_roles.id'], name=op.f('fk_rbac_membership_roles_role_id_rbac_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rbac_membership_roles')),
    sa.UniqueConstraint('membership_id', 'role_id', name='uq_membership_role')
    )
    op.create_index(op.f('ix_rbac_membership_roles_membership_id'), 'rbac_membership_roles', ['membership_id'], unique=False)
    op.create_index(op.f('ix_rbac_membership_roles_role_id'), 'rbac_membership_roles', ['role_id'], unique=False)
    op.create_table('rbac_role_permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['rbac_permissions.id'], name=op.f('fk_rbac_role_permissions_permission_id_rbac_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['rbac_roles.id'], name=op.f('fk_rbac_role_permissions_role_id_rbac_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rbac_role_permissions')),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_index(op.f('ix_rbac_role_permissions_permission_id'), 'rbac_role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_rbac_role_permissions_role_id'), 'rbac_role_permissions', ['role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rbac_role_permissions_role_id'), table_name='rbac_role_permissions')
    op.drop_index(op.f('ix_rbac_role_permissions_permission_id'), table_name='rbac_role_permissions')
    op.drop_table('rbac_role_permissions')
    op.drop_index(op.f('ix_rbac_membership_roles_role_id'), table_name='rbac_membership_roles')
    op.drop_index(op.f('ix_rbac_membership_roles_membership_id'), table_name='rbac_membership_roles')
    op.drop_table('rbac_membership_roles')
    op.drop_index(op.f('ix_rbac_roles_organization_id'), table_name='rbac_roles')
    op.drop_table('rbac_roles')
    op.drop_index(op.f('ix_rbac_permissions_key'), table_name='rbac_permissions')
    op.drop_table('rbac_permissions')
    # ### end Alembic commands ###
