"""add platform notifications

Revision ID: 91a926c78489
Revises: 2dc2d1ed5d96
Create Date: 2026-07-21 18:17:04.018093+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.database.types

# revision identifiers, used by Alembic.
revision: str = '91a926c78489'
down_revision: Union[str, Sequence[str], None] = '2dc2d1ed5d96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('type', sa.Enum('INFO', 'WARNING', 'ALERT', 'SUCCESS', name='notification_type_enum'), server_default='INFO', nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('metadata_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity_users.id'], name=op.f('fk_platform_notifications_user_id_identity_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_notifications'))
    )
    op.create_index(op.f('ix_platform_notifications_user_id'), 'platform_notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platform_notifications_user_id'), table_name='platform_notifications')
    op.drop_table('platform_notifications')
    # ### end Alembic commands ###
