"""add platform settings

Revision ID: 9237f4f28ee3
Revises: 91a926c78489
Create Date: 2026-07-21 19:53:09.827788+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app.database.types

# revision identifiers, used by Alembic.
revision: str = '9237f4f28ee3'
down_revision: Union[str, Sequence[str], None] = '91a926c78489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('platform_name', sa.String(length=255), server_default='OmniVote', nullable=False),
    sa.Column('maintenance_mode', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('allow_public_registration', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('branding', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('theme_configuration', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('feature_toggles', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('public_urls', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('smtp_credentials_encrypted', sa.String(), nullable=True),
    sa.Column('email_provider_api_keys_encrypted', sa.String(), nullable=True),
    sa.Column('sms_provider_api_keys_encrypted', sa.String(), nullable=True),
    sa.Column('storage_credentials_encrypted', sa.String(), nullable=True),
    sa.Column('oauth_client_secrets_encrypted', sa.String(), nullable=True),
    sa.Column('third_party_service_tokens_encrypted', sa.String(), nullable=True),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_settings'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform_settings')
    # ### end Alembic commands ###
