"""add_voting_models

Revision ID: 9b66dcb50b0f
Revises: de6186fce7eb
Create Date: 2026-07-23 14:54:51.238504+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.database.types


# revision identifiers, used by Alembic.
revision: str = '9b66dcb50b0f'
down_revision: Union[str, Sequence[str], None] = 'de6186fce7eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ballots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('election_id', sa.Uuid(), nullable=False),
    sa.Column('receipt_code', sa.String(length=50), nullable=False),
    sa.Column('cast_at', app.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], name=op.f('fk_ballots_election_id_elections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ballots'))
    )
    op.create_index(op.f('ix_ballots_election_id'), 'ballots', ['election_id'], unique=False)
    op.create_index(op.f('ix_ballots_receipt_code'), 'ballots', ['receipt_code'], unique=True)
    op.create_table('voting_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('election_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('voter_identifier', sa.String(length=255), nullable=True),
    sa.Column('verification_method', sa.Enum('PLATFORM_ACCOUNT', 'STUDENT_ID', 'EMPLOYEE_ID', 'EMAIL', 'PHONE_NUMBER', 'USSD', 'PUBLIC', name='verificationmethod'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUBMITTED', 'EXPIRED', 'ABANDONED', name='votingsessionstatus'), nullable=False),
    sa.Column('expires_at', app.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('completed_at', app.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], name=op.f('fk_voting_sessions_election_id_elections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['identity_users.id'], name=op.f('fk_voting_sessions_user_id_identity_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voting_sessions'))
    )
    op.create_index(op.f('ix_voting_sessions_election_id'), 'voting_sessions', ['election_id'], unique=False)
    op.create_index(op.f('ix_voting_sessions_status'), 'voting_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_voting_sessions_user_id'), 'voting_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_voting_sessions_voter_identifier'), 'voting_sessions', ['voter_identifier'], unique=False)
    op.create_table('ballot_selections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ballot_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['ballot_id'], ['ballots.id'], name=op.f('fk_ballot_selections_ballot_id_ballots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['election_candidates.id'], name=op.f('fk_ballot_selections_candidate_id_election_candidates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['election_categories.id'], name=op.f('fk_ballot_selections_category_id_election_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ballot_selections'))
    )
    op.create_index(op.f('ix_ballot_selections_ballot_id'), 'ballot_selections', ['ballot_id'], unique=False)
    op.create_index(op.f('ix_ballot_selections_candidate_id'), 'ballot_selections', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_ballot_selections_category_id'), 'ballot_selections', ['category_id'], unique=False)
    op.create_table('voting_selections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['election_candidates.id'], name=op.f('fk_voting_selections_candidate_id_election_candidates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['election_categories.id'], name=op.f('fk_voting_selections_category_id_election_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['voting_sessions.id'], name=op.f('fk_voting_selections_session_id_voting_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voting_selections'))
    )
    op.create_index(op.f('ix_voting_selections_candidate_id'), 'voting_selections', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_voting_selections_category_id'), 'voting_selections', ['category_id'], unique=False)
    op.create_index(op.f('ix_voting_selections_session_id'), 'voting_selections', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voting_selections_session_id'), table_name='voting_selections')
    op.drop_index(op.f('ix_voting_selections_category_id'), table_name='voting_selections')
    op.drop_index(op.f('ix_voting_selections_candidate_id'), table_name='voting_selections')
    op.drop_table('voting_selections')
    op.drop_index(op.f('ix_ballot_selections_category_id'), table_name='ballot_selections')
    op.drop_index(op.f('ix_ballot_selections_candidate_id'), table_name='ballot_selections')
    op.drop_index(op.f('ix_ballot_selections_ballot_id'), table_name='ballot_selections')
    op.drop_table('ballot_selections')
    op.drop_index(op.f('ix_voting_sessions_voter_identifier'), table_name='voting_sessions')
    op.drop_index(op.f('ix_voting_sessions_user_id'), table_name='voting_sessions')
    op.drop_index(op.f('ix_voting_sessions_status'), table_name='voting_sessions')
    op.drop_index(op.f('ix_voting_sessions_election_id'), table_name='voting_sessions')
    op.drop_table('voting_sessions')
    op.drop_index(op.f('ix_ballots_receipt_code'), table_name='ballots')
    op.drop_index(op.f('ix_ballots_election_id'), table_name='ballots')
    op.drop_table('ballots')
    # ### end Alembic commands ###
