"""election_engine_foundation

Revision ID: ab6826970a56
Revises: 9237f4f28ee3
Create Date: 2026-07-22 00:53:24.754537+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision: str = 'ab6826970a56'
down_revision: Union[str, Sequence[str], None] = '9237f4f28ee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('election_type', sa.Enum('GENERAL_ELECTION', 'REFERENDUM', 'SURVEY', 'POLL', 'AWARD_VOTING', 'COMMITTEE_ELECTION', 'CUSTOM', name='electiontype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIGURED', 'PUBLISHED', 'VOTING_OPEN', 'VOTING_CLOSED', 'COUNTING', 'RESULTS_PUBLISHED', 'ARCHIVED', 'CANCELLED', name='electionstatus'), nullable=False),
    sa.Column('visibility', sa.Enum('PRIVATE', 'ORGANIZATION_ONLY', 'PUBLIC', 'UNLISTED', name='visibility'), nullable=False),
    sa.Column('registration_opens_at', app.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('registration_closes_at', app.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('voting_opens_at', app.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('voting_closes_at', app.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('results_publish_at', app.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('allow_anonymous_voting', sa.Boolean(), nullable=False),
    sa.Column('allow_result_preview', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', app.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['identity_users.id'], name=op.f('fk_elections_created_by_identity_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['identity_users.id'], name=op.f('fk_elections_deleted_by_identity_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_elections_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['identity_users.id'], name=op.f('fk_elections_updated_by_identity_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_elections'))
    )
    op.create_index(op.f('ix_elections_is_deleted'), 'elections', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_elections_organization_id'), 'elections', ['organization_id'], unique=False)
    op.create_index(op.f('ix_elections_public_id'), 'elections', ['public_id'], unique=True)
    op.create_index(op.f('ix_elections_slug'), 'elections', ['slug'], unique=False)
    op.create_index(op.f('ix_elections_status'), 'elections', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_elections_status'), table_name='elections')
    op.drop_index(op.f('ix_elections_slug'), table_name='elections')
    op.drop_index(op.f('ix_elections_public_id'), table_name='elections')
    op.drop_index(op.f('ix_elections_organization_id'), table_name='elections')
    op.drop_index(op.f('ix_elections_is_deleted'), table_name='elections')
    op.drop_table('elections')
    # ### end Alembic commands ###
