"""add_identity_platform_models

Revision ID: b5878e978a88
Revises: 4862091312e5
Create Date: 2026-07-18 02:41:45.155644+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import app


# revision identifiers, used by Alembic.
revision: str = 'b5878e978a88'
down_revision: Union[str, Sequence[str], None] = '4862091312e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PENDING_VERIFICATION', 'SUSPENDED', 'DISABLED', name='account_status_enum'), server_default='PENDING_VERIFICATION', nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_login_at', app.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', app.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_users'))
    )
    op.create_index(op.f('ix_identity_users_email'), 'identity_users', ['email'], unique=True)
    op.create_index(op.f('ix_identity_users_username'), 'identity_users', ['username'], unique=True)
    op.create_table('identity_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('password_hash', sa.String(length=1024), nullable=False),
    sa.Column('password_updated_at', app.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_until', app.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['identity_users.id'], name=op.f('fk_identity_credentials_user_id_identity_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_credentials')),
    sa.UniqueConstraint('user_id', name=op.f('uq_identity_credentials_user_id'))
    )
    op.create_table('identity_password_reset_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=1024), nullable=False),
    sa.Column('expires_at', app.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('used_at', app.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity_users.id'], name=op.f('fk_identity_password_reset_tokens_user_id_identity_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_password_reset_tokens'))
    )
    op.create_index(op.f('ix_identity_password_reset_tokens_token_hash'), 'identity_password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_identity_password_reset_tokens_user_id'), 'identity_password_reset_tokens', ['user_id'], unique=False)
    op.create_table('identity_security_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=1024), nullable=True),
    sa.Column('metadata_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity_users.id'], name=op.f('fk_identity_security_events_user_id_identity_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_security_events'))
    )
    op.create_index(op.f('ix_identity_security_events_created_at'), 'identity_security_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_identity_security_events_event_type'), 'identity_security_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_identity_security_events_user_id'), 'identity_security_events', ['user_id'], unique=False)
    op.create_table('identity_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=1024), nullable=False),
    sa.Column('device_information', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=1024), nullable=True),
    sa.Column('expires_at', app.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', app.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity_users.id'], name=op.f('fk_identity_sessions_user_id_identity_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_sessions'))
    )
    op.create_index(op.f('ix_identity_sessions_refresh_token_hash'), 'identity_sessions', ['refresh_token_hash'], unique=True)
    op.create_index(op.f('ix_identity_sessions_user_id'), 'identity_sessions', ['user_id'], unique=False)
    op.create_table('identity_verification_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=1024), nullable=False),
    sa.Column('expires_at', app.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('used_at', app.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity_users.id'], name=op.f('fk_identity_verification_tokens_user_id_identity_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_verification_tokens'))
    )
    op.create_index(op.f('ix_identity_verification_tokens_token_hash'), 'identity_verification_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_identity_verification_tokens_user_id'), 'identity_verification_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_identity_verification_tokens_user_id'), table_name='identity_verification_tokens')
    op.drop_index(op.f('ix_identity_verification_tokens_token_hash'), table_name='identity_verification_tokens')
    op.drop_table('identity_verification_tokens')
    op.drop_index(op.f('ix_identity_sessions_user_id'), table_name='identity_sessions')
    op.drop_index(op.f('ix_identity_sessions_refresh_token_hash'), table_name='identity_sessions')
    op.drop_table('identity_sessions')
    op.drop_index(op.f('ix_identity_security_events_user_id'), table_name='identity_security_events')
    op.drop_index(op.f('ix_identity_security_events_event_type'), table_name='identity_security_events')
    op.drop_index(op.f('ix_identity_security_events_created_at'), table_name='identity_security_events')
    op.drop_table('identity_security_events')
    op.drop_index(op.f('ix_identity_password_reset_tokens_user_id'), table_name='identity_password_reset_tokens')
    op.drop_index(op.f('ix_identity_password_reset_tokens_token_hash'), table_name='identity_password_reset_tokens')
    op.drop_table('identity_password_reset_tokens')
    op.drop_table('identity_credentials')
    op.drop_index(op.f('ix_identity_users_username'), table_name='identity_users')
    op.drop_index(op.f('ix_identity_users_email'), table_name='identity_users')
    op.drop_table('identity_users')
    # ### end Alembic commands ###
