"""separate_verification_status

Revision ID: bcbaa7685117
Revises: 6f8bacc33dda
Create Date: 2026-07-19 14:53:04.677655+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcbaa7685117'
down_revision: Union[str, Sequence[str], None] = '6f8bacc33dda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    verification_enum = sa.Enum('UNVERIFIED', 'PENDING_VERIFICATION', 'VERIFIED', 'REJECTED', name='organization_verification_status_enum')
    verification_enum.create(op.get_bind())
    op.add_column('organizations', sa.Column('verification_status', verification_enum, nullable=False, server_default='UNVERIFIED'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'verification_status')
    verification_enum = sa.Enum('UNVERIFIED', 'PENDING_VERIFICATION', 'VERIFIED', 'REJECTED', name='organization_verification_status_enum')
    verification_enum.drop(op.get_bind())
    # ### end Alembic commands ###
