"""Add tokens

Revision ID: dc9032f56abc
Revises: b5878e978a88
Create Date: 2026-07-18 11:13:36.741127+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc9032f56abc'
down_revision: Union[str, Sequence[str], None] = 'b5878e978a88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity_users.id'], name=op.f('fk_password_reset_tokens_user_id_identity_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token', name=op.f('pk_password_reset_tokens'))
    )
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('verification_tokens',
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity_users.id'], name=op.f('fk_verification_tokens_user_id_identity_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token', name=op.f('pk_verification_tokens'))
    )
    op.create_index(op.f('ix_verification_tokens_token'), 'verification_tokens', ['token'], unique=False)
    op.create_index(op.f('ix_verification_tokens_user_id'), 'verification_tokens', ['user_id'], unique=False)
    op.drop_index(op.f('ix_identity_verification_tokens_token_hash'), table_name='identity_verification_tokens')
    op.drop_index(op.f('ix_identity_verification_tokens_user_id'), table_name='identity_verification_tokens')
    op.drop_table('identity_verification_tokens')
    op.drop_index(op.f('ix_identity_password_reset_tokens_token_hash'), table_name='identity_password_reset_tokens')
    op.drop_index(op.f('ix_identity_password_reset_tokens_user_id'), table_name='identity_password_reset_tokens')
    op.drop_table('identity_password_reset_tokens')
    op.alter_column('identity_security_events', 'metadata_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('identity_security_events', 'metadata_payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_table('identity_password_reset_tokens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity_users.id'], name=op.f('fk_identity_password_reset_tokens_user_id_identity_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_password_reset_tokens'))
    )
    op.create_index(op.f('ix_identity_password_reset_tokens_user_id'), 'identity_password_reset_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_identity_password_reset_tokens_token_hash'), 'identity_password_reset_tokens', ['token_hash'], unique=True)
    op.create_table('identity_verification_tokens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['identity_users.id'], name=op.f('fk_identity_verification_tokens_user_id_identity_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_verification_tokens'))
    )
    op.create_index(op.f('ix_identity_verification_tokens_user_id'), 'identity_verification_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_identity_verification_tokens_token_hash'), 'identity_verification_tokens', ['token_hash'], unique=True)
    op.drop_index(op.f('ix_verification_tokens_user_id'), table_name='verification_tokens')
    op.drop_index(op.f('ix_verification_tokens_token'), table_name='verification_tokens')
    op.drop_table('verification_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
