"""Add ElectionCandidate model

Revision ID: de6186fce7eb
Revises: 5286460ccbcd
Create Date: 2026-07-23 03:40:11.363119+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision: str = 'de6186fce7eb'
down_revision: Union[str, Sequence[str], None] = '5286460ccbcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('election_candidates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('election_category_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_number', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('photo', sa.String(length=1000), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('manifesto', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'WITHDRAWN', 'DISQUALIFIED', name='candidatestatus'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', app.database.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.database.types.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deleted_by'], ['identity_users.id'], name=op.f('fk_election_candidates_deleted_by_identity_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['election_category_id'], ['election_categories.id'], name=op.f('fk_election_candidates_election_category_id_election_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_election_candidates'))
    )
    op.create_index(op.f('ix_election_candidates_election_category_id'), 'election_candidates', ['election_category_id'], unique=False)
    op.create_index(op.f('ix_election_candidates_is_deleted'), 'election_candidates', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_election_candidates_status'), 'election_candidates', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_election_candidates_status'), table_name='election_candidates')
    op.drop_index(op.f('ix_election_candidates_is_deleted'), table_name='election_candidates')
    op.drop_index(op.f('ix_election_candidates_election_category_id'), table_name='election_candidates')
    op.drop_table('election_candidates')
    # ### end Alembic commands ###
