"""Add versioning

Revision ID: ea256be1859d
Revises: 9b66dcb50b0f
Create Date: 2026-07-24 20:41:15.905629+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea256be1859d'
down_revision: Union[str, Sequence[str], None] = '9b66dcb50b0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ballots', sa.Column('ballot_schema_version', sa.Integer(), server_default='1', nullable=False))
    op.add_column('elections', sa.Column('voting_engine_version', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('elections', 'voting_engine_version')
    op.drop_column('ballots', 'ballot_schema_version')
    # ### end Alembic commands ###
